# Generated by Django 5.2.3 on 2026-01-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issues_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=10)),
                ('row_index', models.PositiveIntegerField()),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('first_price', models.PositiveIntegerField(blank=True, null=True)),
                ('second_price', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_flag', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('LOW', 'LowConfidence')], default='OK', max_length=12)),
                ('number_flag', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('LOW', 'LowConfidence')], default='OK', max_length=12)),
                ('first_flag', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('LOW', 'LowConfidence')], default='OK', max_length=12)),
                ('second_flag', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('LOW', 'LowConfidence')], default='OK', max_length=12)),
                ('conf_number', models.FloatField(blank=True, null=True)),
                ('conf_first', models.FloatField(blank=True, null=True)),
                ('conf_second', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scanner.document')),
            ],
            options={
                'ordering': ('side', 'row_index'),
                'unique_together': {('document', 'side', 'row_index')},
            },
        ),
    ]
