# Generated by Django 5.2.3 on 2026-01-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_document_issues_count_document_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commission_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='commission_type',
            field=models.CharField(choices=[('PERCENT', 'Percent (%)'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='commission_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='net_bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='total_after_commission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='total_first',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='total_prize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='total_second',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_number', models.BigIntegerField()),
                ('prize_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='scanner.document')),
            ],
        ),
    ]
